from .path_config import *

__all__ = [
    "VIDEO_SAMPLE1_DIR",
    "VIDEO_SAMPLE2_DIR",
    "VIDEO_SAMPLE3_DIR",
    "VIDEO_SAMPLE4_DIR",
    "VIDEO_SAMPLE5_DIR",
    "VOLLEYBALL_DETECTION_DIR",
    "VOLLEYBALL_TRACKING_DIR",

]
