defaults:
  - _self_
  - transforms: default_transforms.yaml

batch_size: 128
num_workers: 4
pin_memory: false

num_epochs: 25                # ⬇️ from 100
learning_rate: 5e-5           # ⬇️ from 1e-4
weight_decay: 0.05            # ⬆️ new

lr_scheduler:
  name: CosineAnnealingLR
  T_max: ${num_epochs}
  eta_min: 1e-7               # ⬇️ from 1e-5

head_lr_multiplier: 5         # ⬇️ from 10

label_smoothing: 0.1          # ⬆️ new
early_stopping_patience: 5    # ⬆️ new

 
 


model:
  name: "resnet50"
  pretrained: true
  weights: "DEFAULT"

device: cuda
seed: 42

# --- Output Directory ---
hydra:
  run:
    dir: ./runs/baseline1/${now:%Y-%m-%d}/${now:%H-%M-%S}