defaults:
  - _self_
  - transforms: default_transforms.yaml

batch_size: 64
num_workers: 4
pin_memory: false

# --- Stage 1: Linear probe (head only) ---
warmup_epochs: 5
warmup_lr: 1e-3

# --- Stage 2: Full fine-tune (differential LR) ---
num_epochs: 50
learning_rate: 1e-4 # increasing the learning rate for the SGD optimizer
weight_decay: 0.05
head_lr_multiplier: 2

lr_scheduler:
  name: CosineAnnealingLR
  T_max: ${num_epochs}
  eta_min: 1e-6

label_smoothing: 0.1
early_stopping_patience: 10

model:
  # name: "resnet50" # underfits the data 
  
  name: "resnet101"
  pretrained: true
  weights: "DEFAULT"

device: cuda
seed: 42

hydra:
  run:
    dir: ./runs/baseline1/${now:%Y-%m-%d}/${now:%H-%M-%S}